version: '3.8'
services:
  php:
    image: php:8.1-apache
    container_name: spotmap_php
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0
    container_name: spotmap_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spotmap
      MYSQL_USER: spotmap
      MYSQL_PASSWORD: spotmappw
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "33060:3306"

volumes:
  db_data:
